In [1]:
#1.
import requests
import pandas as pd
import numpy

In [2]:
url='https://arxiv.org/search/?query=healthcare&searchtype=all&source=header'

In [3]:
response = requests.get(url)
response

<Response [200]>

In [5]:
import selenium
from selenium.webdriver import Firefox



In [6]:
browser=Firefox()

In [7]:
browser.get(url)

In [8]:
article=browser.find_elements_by_tag_name('li[class="arxiv-result"]')
#article_next=browser.find_element_by_tag_name('a[class="pagination-next"]').get_attribute('href')

In [16]:
all_the_articles = []
condition=True

while condition:
    article=browser.find_elements_by_tag_name('li[class="arxiv-result"]')
    for a_article in article:
        arxiv_id = a_article.find_elements_by_tag_name('a')[0].text
        pdf = a_article.find_elements_by_tag_name('a')[1].get_attribute('href')
        title = a_article.find_element_by_tag_name('p[class="title is-5 mathjax"]').text
        
        authors = a_article.find_element_by_tag_name('p[class="authors"]').text
        abstract = a_article.find_element_by_tag_name('p[class="abstract mathjax"]').text
        submitted =a_article.find_element_by_tag_name('p[class="is-size-7"]').text
    
        result = [arxiv_id,pdf,title,authors,abstract,submitted]
        all_the_articles.append(result)
    try:
        browser.find_element_by_tag_name('a[class="pagination-next"]').click()
    except:
        condition=False

In [10]:
all_articles_final=pd.DataFrame(all_the_articles)

In [11]:
all_articles_final.columns=['arxiv_id','pdf_link','title','authors','abstract','submitted']

In [12]:
all_articles_final

arxiv_id                          pdf_link  \
0   arXiv:2010.10328  https://arxiv.org/pdf/2010.10328   
1   arXiv:2010.10285  https://arxiv.org/pdf/2010.10285   
2   arXiv:2010.10269  https://arxiv.org/pdf/2010.10269   
3   arXiv:2010.10112  https://arxiv.org/pdf/2010.10112   
4   arXiv:2010.09909  https://arxiv.org/pdf/2010.09909   
5   arXiv:2010.09593  https://arxiv.org/pdf/2010.09593   
6   arXiv:2010.09427  https://arxiv.org/pdf/2010.09427   
7   arXiv:2010.09394  https://arxiv.org/pdf/2010.09394   
8   arXiv:2010.08866  https://arxiv.org/pdf/2010.08866   
9   arXiv:2010.08793  https://arxiv.org/pdf/2010.08793   
10  arXiv:2010.08698  https://arxiv.org/pdf/2010.08698   
11  arXiv:2010.08660  https://arxiv.org/pdf/2010.08660   
12  arXiv:2010.08570  https://arxiv.org/pdf/2010.08570   
13  arXiv:2010.08250  https://arxiv.org/pdf/2010.08250   
14  arXiv:2010.08124  https://arxiv.org/pdf/2010.08124   
15  arXiv:2010.08100  https://arxiv.org/pdf/2010.08100   
16  arXiv:2010.08056  https://arxiv.org/pdf/2010.08056   
17  arXiv:2010.08031  https://arxiv.org/pdf/2010.08031   
18  arXiv:2010.07866  https://arxiv.org/pdf/2010.07866   
19  arXiv:2010.07437  https://arxiv.org/pdf/2010.07437   
20  arXiv:2010.07194  https://arxiv.org/pdf/2010.07194   
21  arXiv:2010.07036  https://arxiv.org/pdf/2010.07036   
22  arXiv:2010.07029  https://arxiv.org/pdf/2010.07029   
23  arXiv:2010.06989  https://arxiv.org/pdf/2010.06989   
24  arXiv:2010.06820  https://arxiv.org/pdf/2010.06820   
25  arXiv:2010.06430  https://arxiv.org/pdf/2010.06430   
26  arXiv:2010.06418  https://arxiv.org/pdf/2010.06418   
27  arXiv:2010.06296  https://arxiv.org/pdf/2010.06296   
28  arXiv:2010.06177  https://arxiv.org/pdf/2010.06177   
29  arXiv:2010.06059  https://arxiv.org/pdf/2010.06059   
30  arXiv:2010.05855  https://arxiv.org/pdf/2010.05855   
31  arXiv:2010.05635  https://arxiv.org/pdf/2010.05635   
32  arXiv:2010.05349  https://arxiv.org/pdf/2010.05349   
33  arXiv:2010.05247  https://arxiv.org/pdf/2010.05247   
34  arXiv:2010.05164  https://arxiv.org/pdf/2010.05164   
35  arXiv:2010.05079  https://arxiv.org/pdf/2010.05079   
36  arXiv:2010.04652  https://arxiv.org/pdf/2010.04652   
37  arXiv:2010.04420  https://arxiv.org/pdf/2010.04420   
38  arXiv:2010.03805  https://arxiv.org/pdf/2010.03805   
39  arXiv:2010.03671  https://arxiv.org/pdf/2010.03671   
40  arXiv:2010.03624  https://arxiv.org/pdf/2010.03624   
41  arXiv:2010.03324  https://arxiv.org/pdf/2010.03324   
42  arXiv:2010.03114  https://arxiv.org/pdf/2010.03114   
43  arXiv:2010.02819  https://arxiv.org/pdf/2010.02819   
44  arXiv:2010.02742  https://arxiv.org/pdf/2010.02742   
45  arXiv:2010.02715  https://arxiv.org/pdf/2010.02715   
46  arXiv:2010.02256  https://arxiv.org/pdf/2010.02256   
47  arXiv:2010.02141  https://arxiv.org/pdf/2010.02141   
48  arXiv:2010.01496  https://arxiv.org/pdf/2010.01496   
49  arXiv:2010.01479  https://arxiv.org/pdf/2010.01479   

                                                title  \
0   Interpretable Deep Learning for Automatic Diag...   
1   Leveraging Technology for Healthcare and Retai...   
2   Towards new forms of particle sensing and mani...   
3   University Operations During a Pandemic: A Fle...   
4   The Role of Robotics in Infectious Disease Crises   
5   Multiclass Wound Image Classification using an...   
6   A Privacy-Preserving Data Inference Framework ...   
7   Knowledge Graph-based Question Answering with ...   
8   MyWear: A Smart Wear for Continuous Body Vital...   
9   Threats and Corrective Measures for IoT Securi...   
10  Is Image Encoding Beneficial for Deep Learning...   
11  Semantics of the Black-Box: Can knowledge grap...   
12  Generating Fact Checking Summaries for Web Claims   
13  Biodegradable Polymeric Micro/Nano-Structures ...   
14  Risk-Aware Decision Making in Service Robots t...   
15  When Virtual Therapy and Art Meet: A Case Stud...   
16  IoT Platform for COVID-19 Prevention and Contr...   
17  QReLU and m-QReLU: Two 

In [80]:
#######################################################


In [22]:
#2. Ranking the query with abstracts in the dataset
search = pd.read_csv('C:/Users/Ajit/Desktop/Web_mining_yegin/midterm.csv')
search_abstract=search['abstract']
search_abstract   #only abstracts


0       Abstract: Acute and chronic wounds are a chall...
1       Abstract: Privacy protection in electronic hea...
2       Abstract: Question Answering (QA) on Electroni...
3       Abstract: Smart healthcare which is built as… ...
4       Abstract: …discussed in detail. This paper als...
                              ...                        
1885    Abstract: …is to maximize their cross fertiliz...
1886    Abstract: …emerging grid technology, the aim o...
1887    Abstract: …EU-funded MammoGrid project is, in ...
1888    Abstract: …services. However, once the data mo...
1889    Abstract: Good communication is vital in healt...
Name: abstract, Length: 1890, dtype: object

In [24]:
search_Abstract

NameError: name 'search_Abstract' is not defined

In [25]:
#cleaning
import nltk
import re
#nltk.download('stopwords')
stopword = nltk.corpus.stopwords.words('english')   ## Our stop words
wn = nltk.WordNetLemmatizer()
sm = nltk.PorterStemmer()

def clean(text):
    text=re.sub(r'[^\w\s]',' ',text).lower()   ### Remove punctuation by removing non-space alpha-num characters
    words=re.split(r'\W+', text)  ### Split by remaining non-alphanumeric characters 
    non_stop_words=[word for word in words if word not in stopword]        ### Remove stopwords
    lem_words= [sm.stem(word) for word in non_stop_words] 
    clean_text= ' '.join(lem_words)
    return clean_text

In [26]:
search_abstract=search_abstract.apply(clean)

In [27]:
search_abstract

0       abstract acut chronic wound challeng healthcar...
1       abstract privaci protect electron healthcar ap...
2       abstract question answer qa electron health re...
3                          abstract smart healthcar built
4       abstract discuss detail paper also present rol...
                              ...                        
1885    abstract maxim cross fertil context environ da...
1886    abstract emerg grid technolog aim mammogrid 1 ...
1887    abstract eu fund mammogrid project light emerg...
1888    abstract servic howev data model fix difficult...
1889    abstract good commun vital healthcar among hea...
Name: abstract, Length: 1890, dtype: object

In [28]:
from sklearn.feature_extraction.text import CountVectorizer

count_vectorizer=CountVectorizer()

vsm=count_vectorizer.fit_transform(search_abstract)
pd.DataFrame(vsm.todense(), columns=count_vectorizer.get_feature_names())

vocab=count_vectorizer.get_feature_names()
vocab

['000',
 '001',
 '01',
 '03626',
 '05',
 '10',
 '100',
 '1000',
 '100x',
 '101',
 '108',
 '10gi',
 '10x',
 '11',
 '117',
 '12',
 '120',
 '125',
 '1260',
 '13',
 '130',
 '14',
 '140',
 '147',
 '149',
 '14i',
 '15',
 '1501',
 '158',
 '16',
 '163',
 '17',
 '1700',
 '171r2',
 '172',
 '173',
 '179',
 '18',
 '180',
 '1800',
 '18f',
 '18th',
 '19',
 '1959',
 '196',
 '1990',
 '1999',
 '1bn',
 '1e',
 '1m',
 '1st',
 '1t',
 '20',
 '200',
 '2000',
 '2001',
 '2002',
 '2005',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2013',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020',
 '2024',
 '2030',
 '2042',
 '2050',
 '21',
 '21st',
 '22',
 '24',
 '242',
 '25',
 '250',
 '25010',
 '253',
 '25th',
 '260',
 '260k',
 '27',
 '28',
 '282',
 '28447',
 '2887',
 '29',
 '295',
 '2d',
 '30',
 '300',
 '307',
 '30k',
 '317',
 '33',
 '35',
 '350',
 '366',
 '375',
 '383',
 '398',
 '3d',
 '3gpp',
 '3t',
 '400',
 '42',
 '420',
 '421',
 '43',
 '436',
 '45',
 '450',
 '46',
 '467',
 '468',
 '47',
 '471',
 '48'

In [29]:
import pandas as pd
import numpy as np

In [187]:
#pd.DataFrame(vsm.todense(), columns=count_vectorizer.get())

In [30]:
query=['natural language processing']

## Vectorize the query
query_vector=count_vectorizer.transform(query)

query_vector.todense()

matrix([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [31]:
from sklearn.metrics.pairwise import cosine_similarity

In [32]:
similarity_vals=cosine_similarity(query_vector, vsm)[0]

In [33]:
similarity_vals

array([0., 0., 0., ..., 0., 0., 0.])

In [34]:
rankings=np.argsort(similarity_vals)[::-1]
rankings

array([1889,  634,  622, ..., 1265, 1266,    0], dtype=int64)

In [35]:
processed_abstract =[search_abstract[i]for i in rankings]
processed_abstract

['abstract good commun vital healthcar among healthcar profession healthcar profession patient well written document describ explain inform structur databas may easier comprehend edifi',
 'abstract emerg technolog blockchain achiev great success numer applic scenario intellig healthcar smart citi howev long stand bottleneck hinder develop massiv resourc consumpt attribut distribut storag comput method make blockchain suffer insuffici',
 'abstract electron health record ehr improv mani aspect healthcar allow easier patient manag medic provid blockchain propos promis solut support electron health record ehr also link scalabl concern support real world',
 'abstract cancer still one devast diseas time one way automat classifi tumor sampl analyz deriv molecular inform e gene express signatur work aim distinguish three differ type cancer thyroid skin stomach compar perform denois autoencod dae use weight initializa',
 'abstract polici high qualiti gener model even observ irrelev plan b batch

In [36]:
rankings_search = pd.DataFrame(rankings)
rankings_search


0
0     1889
1      634
2      622
3      623
4      624
...    ...
1885  1263
1886  1264
1887  1265
1888  1266
1889     0

[1890 rows x 1 columns]

In [204]:
#################################

In [38]:
#3. 
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vector = TfidfVectorizer()
tfidf_processed=tfidf_vector.fit_transform(processed_abstract)
tfidf_processed

<1890x5517 sparse matrix of type '<class 'numpy.float64'>'
	with 56209 stored elements in Compressed Sparse Row format>

In [41]:
import pandas as pd
array = pd.DataFrame(tfidf_processed.todense(), columns=tfidf_vector.get_feature_names()).head()

In [42]:
query=['natural language processing']

In [44]:
## Vectorize the query
query_vector=tfidf_vector.transform(query)

In [45]:
query_vector

<1x5517 sparse matrix of type '<class 'numpy.float64'>'
	with 0 stored elements in Compressed Sparse Row format>

In [46]:
from sklearn.metrics.pairwise import cosine_similarity

In [47]:
similarity_vals=cosine_similarity(query_vector,tfidf_processed)[0]

In [48]:
similarity_vals

array([0., 0., 0., ..., 0., 0., 0.])

In [49]:
rankings1=np.argsort(similarity_vals)[::-1]

In [50]:
rankings1

array([1889,  634,  622, ..., 1265, 1266,    0], dtype=int64)

In [51]:
[processed_abstract[i] for i in rankings1]

['abstract acut chronic wound challeng healthcar system around world affect mani peopl live annual wound classif key step wound diagnosi would help clinician identifi optim treatment procedur henc high perform classifi assist specialist field classifi wound l',
 'abstract platform prefer util achiev goal due ubiquit sens abil seamless connect iot technolog chang live smart healthcar smart home smart citi aim build conveni intellig commun paper present iot could incorpor epidem preventi',
 'abstract idea other differ issu one preval issu covid 19 pandem detect track topic kind issu would help govern healthcar compani deal phenomenon paper propos novel commun cluster approach call comstreamclust cluster sub topic insid broader',
 'abstract heart causal structur learn observ data lie deceivingli simpl question given two statist depend random variabl one causal effect imposs answer use statist depend test alon requir make addit assumpt propos sever fast simpl criteria distinguish caus effe

In [52]:
# tf-Idf fits better better thanCount-Vectorization$

SyntaxError: invalid syntax (<ipython-input-52-54f513c64002>, line 1)

In [ ]:
# 4
# trying to implement HashingVectorizer

In [53]:
from sklearn.feature_extraction.text import HashingVectorizer

vectorizer = HashingVectorizer()
X = vectorizer.fit_transform(processed_abstract)
print(X.shape)

pd.DataFrame(vsm.todense(), columns=count_vectorizer.get_feature_names())

(1890, 1048576)


000  001  01  03626  05  10  100  1000  100x  101  ...  youtub  z3  zee  \
0       0    0   0      0   0   0    0     0     0    0  ...       0   0    0   
1       0    0   0      0   0   0    0     0     0    0  ...       0   0    0   
2       0    0   0      0   0   0    0     0     0    0  ...       0   0    0   
3       0    0   0      0   0   0    0     0     0    0  ...       0   0    0   
4       0    0   0      0   0   0    0     0     0    0  ...       0   0    0   
...   ...  ...  ..    ...  ..  ..  ...   ...   ...  ...  ...     ...  ..  ...   
1885    0    0   0      0   0   0    0     0     0    0  ...       0   0    0   
1886    0    0   0      0   0   0    0     0     0    0  ...       0   0    0   
1887    0    0   0      0   0   0    0     0     0    0  ...       0   0    0   
1888    0    0   0      0   0   0    0     0     0    0  ...       0   0    0   
1889    0    0   0      0   0   0    0     0     0    0  ...       0   0    0   

      zero  zeu  zf  zika  zin  zip  zteac  
0        0    0   0     0    0    0      0  
1        0    0   0     0    0    0      0  
2        0    0   0     0    0    0      0  
3        0    0   0     0    0    0      0  
4        0    0   0     0    0    0      0  
...    ...  ...  ..   ...  ...  ...    ...  
1885     0    0   0     0    0    0      0  
1886     0    0   0     0    0    0      0  
1887     0    0   0     0    0    0      0  
1888     0    0   0     0    0    0      0  
1889     0    0   0     0    0    0      0  

[1890 rows x 5517 columns]

In [ ]:
#Not a better model than Count and tf-idf